### ISSUE TITLE
Write developer documentation

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/freedombox-todos#1]
Take the current state of the FreedonBox and write up how to use all the parts together.  Include notes on how to create services.  Include notes on who manages each of:
- availability (Freedom Buddy)
- authentication (Apache)
- authorization (OS-level users and groups)

**Comment by jvalleroy** [comment]
I think this is covered by https://wiki.debian.org/FreedomBox/Manual/Developer.
