### ISSUE TITLE
Include a DHCP server

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/freedombox-todos#15]
> Include a DHCP server

**Comment by jvalleroy** [comment]
Current images include dnsmasq, and it's configured to provide DHCP service. I connected a laptop to the eth1 port on Dreamplug to confirm that it's working. So I think this can be closed, feel free to reopen if needed.

**Comment by SunilMohanAdapa** [comment]
I don't know the current status, but from an user's point of view, the following is expected of a DHCP server.

Basic:
- Enabled by default.
- Serve only on 'internal' networks.
- Don't serve on 'external' networks.
- Internal and external networks are the same as zones in Firewall configuration. This is automatically set during initialization.

Advanced:
- Ability to disable DHCP server (multiple FBs on same network can cause problems).
- When a network's zone is changed, serve/don't serve DHCP accordingly.
- Ability to configure the IP address range served.
- Ability to set IP reservations based on request MAC address.

If we agree, we can do these as this task by reopening or by creating a new task for the improvements.
