### ISSUE TITLE
Deliver FreedomBox Debian meta-package

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/freedombox-todos#21]
>Deliver FreedomBox Debian meta-package

**Comment by jvalleroy** [comment]
freedombox-setup isn't a meta-package, but it depends on all the required packages. Is this sufficient, or is there still a need for a meta-package?

**Comment by SunilMohanAdapa** [comment]
It is sufficient, in my opinion.

**Comment by jvalleroy** [comment]
Closing this...please reopen if needed.
