### ISSUE TITLE
Improve GNUTLS

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/freedombox-todos#22]
> Improve GNUTLS

**Comment by jvalleroy** [comment]
One annoying issue in mod_gnutls is that the HTTPS variable is not set:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=514005
We have a workaround for Plinth, but it can fail in some cases where the port is not 443.

**Comment by jvalleroy** [comment]
The HTTPS bug is now fixed. I wonder what other improvements are needed?

**Comment by SunilMohanAdapa** [comment]
The original issue was imported from elsewhere and the intention is not very clear.  I believe that with the above issue fixed, we can close the issue.  Please reopen if necessary.
